### PR TITLE
index.js: enable scrolling

### PR DESCRIPTION
**Pull request by insatomcat**
I found I needed to add this "overflow: visible" style in the body to enable scrolling for this plugin.

### CODE REVIEW

**Comment by TanguyRaufflet** [comment]
I suppose you have the case where there are too many VMs on the table and you can't see the action buttons anymore ? Have you considered adding scrolling only on the VMTable component ?

**Comment by insatomcat** [comment]
Hello, 
Yes indeed that's the pb I have. You can easily reproduce by reducing your browser's window's size.
I don't know anything about react to be honest, so if you feel there's a better way to solve this, do not hesitate to amend this PR.
Thanks.

**Comment by insatomcat** [comment]
nice but it's still weird that there are some space available at the bottom... but still the VM view is truncated
image
Could we stick the command banner at the bottom?

**Comment by dupremathieu** [comment]
I like the idea, but we didn't manage to do it without breaking the responsive designed.
I suggest merging the PR as it and open issue. We have planned to ask a web developer to help us to improve all the plugins UI, we will ask it to do it too.

**Review by dupremathieu — APPROVED** [review]

**Pull request merged**
